import type { LevelConfig } from "./types";

export const level1Config = {
  id: "level-1",
  name: "Station Room",
  dimensions: {
    width: 20,
    depth: 18,
    height: 4.5,
  },
  playerStart: {
    position: [0, 1.7, 1.2],
    rotation: [0, Math.PI, 0],
  },
  topDownCamera: {
    position: [0, 18.5, 0],
    target: [0, 0, 0],
    height: 18.5,
    orthographicSize: 30,
  },
  stations: [
    {
      id: "station-1",
      label: "Station 1",
      position: [-4.5, 0, -3.5],
      rotation: [0, 0.35, 0],
      seatPosition: [-4.5, 0, -2.5],
      monitorPosition: [-4.5, 1.15, -3.9],
    },
    {
      id: "station-2",
      label: "Station 2",
      position: [-1.5, 0, -4.2],
      rotation: [0, 0.12, 0],
      seatPosition: [-1.5, 0, -3.1],
      monitorPosition: [-1.5, 1.15, -4.6],
    },
    {
      id: "station-3",
      label: "Station 3",
      position: [1.5, 0, -4.2],
      rotation: [0, -0.12, 0],
      seatPosition: [1.5, 0, -3.1],
      monitorPosition: [1.5, 1.15, -4.6],
    },
    {
      id: "station-4",
      label: "Station 4",
      position: [4.5, 0, -3.5],
      rotation: [0, -0.35, 0],
      seatPosition: [4.5, 0, -2.5],
      monitorPosition: [4.5, 1.15, -3.9],
    },
    {
      id: "station-5",
      label: "Station 5",
      position: [-4.5, 0, 2.8],
      rotation: [0, 2.8, 0],
      seatPosition: [-4.5, 0, 1.8],
      monitorPosition: [-4.5, 1.15, 3.2],
    },
    {
      id: "station-6",
      label: "Station 6",
      position: [-1.5, 0, 3.6],
      rotation: [0, Math.PI, 0],
      seatPosition: [-1.5, 0, 2.5],
      monitorPosition: [-1.5, 1.15, 4],
    },
    {
      id: "station-7",
      label: "Station 7",
      position: [1.5, 0, 3.6],
      rotation: [0, Math.PI, 0],
      seatPosition: [1.5, 0, 2.5],
      monitorPosition: [1.5, 1.15, 4],
    },
    {
      id: "station-8",
      label: "Station 8",
      position: [4.5, 0, 2.8],
      rotation: [0, -2.8, 0],
      seatPosition: [4.5, 0, 1.8],
      monitorPosition: [4.5, 1.15, 3.2],
    },
  ],
  timerDisplay: {
    id: "central-timer-display",
    position: [0, 2.1, -5.85],
    rotation: [0, 0, 0],
    size: {
      width: 3.2,
      height: 1.4,
    },
  },
  collisionBounds: {
    room: {
      min: [-10, 0, -9],
      max: [10, 4.5, 9],
    },
    blockers: [
      {
        id: "north-station-row",
        label: "North station row",
        min: [-5.6, 0, -5.2],
        max: [5.6, 1.6, -3],
      },
      {
        id: "south-station-row",
        label: "South station row",
        min: [-5.6, 0, 2.2],
        max: [5.6, 1.6, 4.6],
      },
      {
        id: "timer-wall-display",
        label: "Timer display",
        min: [-1.8, 1.2, -6],
        max: [1.8, 2.9, -5.7],
      },
      {
        id: "control-room-west-wall",
        label: "Control room west wall",
        min: [-10.1, 0, -9],
        max: [-9.9, 4.5, 9],
      },
      {
        id: "control-room-east-wall",
        label: "Control room east wall",
        min: [9.9, 0, -9],
        max: [10.1, 4.5, 9],
      },
    ],
  },
  lighting: [
    {
      id: "room-ambient",
      type: "ambient",
      color: "#7fa7ff",
      intensity: 0.38,
    },
    {
      id: "main-overhead",
      type: "directional",
      position: [2, 5, 3],
      target: [0, 0, 0],
      color: "#f4f7ff",
      intensity: 1.15,
    },
    {
      id: "timer-glow-placeholder",
      type: "point",
      position: [0, 2.2, -5.4],
      color: "#57f3ff",
      intensity: 0.9,
    },
  ],
  exits: [
    {
      id: "level-1-studio-door",
      label: "STUDIO",
      targetLevelId: "level-3-recording-studio",
      transitionStyle: "instant",
      position: [-9.86, 1.2, -4.6],
      rotation: [0, Math.PI / 2, 0],
      size: {
        width: 1.55,
        height: 2.15,
      },
    },
    {
      id: "level-1-range-door",
      label: "RANGE",
      targetLevelId: "level-2-range",
      position: [9.86, 1.2, 0],
      rotation: [0, -Math.PI / 2, 0],
      size: {
        width: 1.55,
        height: 2.15,
      },
    },
  ],
  areas: [
    {
      id: "control-room",
      label: "Control Room",
      kind: "control-room",
      bounds: {
        min: [-10, 0, -9],
        max: [10, 4.5, 9],
      },
      spawnPosition: [0, 1.7, 1.2],
      cameraTarget: [0, 1.45, -2.8],
      connectedAreaIds: [],
      status: "active",
    },
  ],
  openings: [],
  traversalSurfaces: [
    {
      id: "control-room-balcony-platform",
      label: "Control room balcony platform",
      kind: "platform",
      areaId: "control-room",
      bounds: {
        min: [-8.6, 0, -8.3],
        max: [8.6, 0.32, -6.2],
      },
      floorHeight: 0.32,
    },
    {
      id: "control-room-left-stair-ramp",
      label: "Control room left stair ramp",
      kind: "ramp",
      areaId: "control-room",
      bounds: {
        min: [-8.125, 0, -6.45],
        max: [-6.275, 0.32, -5.4],
      },
      floorHeight: 0.32,
      ramp: {
        axis: "z",
        lowEdge: "maxZ",
        lowFloorHeight: 0,
        highFloorHeight: 0.32,
      },
    },
    {
      id: "control-room-right-stair-ramp",
      label: "Control room right stair ramp",
      kind: "ramp",
      areaId: "control-room",
      bounds: {
        min: [6.275, 0, -6.45],
        max: [8.125, 0.32, -5.4],
      },
      floorHeight: 0.32,
      ramp: {
        axis: "z",
        lowEdge: "maxZ",
        lowFloorHeight: 0,
        highFloorHeight: 0.32,
      },
    },
  ],
  controlRoomDisplays: [
    {
      id: "hero-main-dashboard",
      label: "Hero Main Dashboard",
      role: "main-dashboard",
      colorRole: "blue-main",
      groupId: "hero-wall",
      priority: 10,
      position: [0, 2.0, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 6.4,
        height: 2.25,
      },
    },
    {
      id: "hero-left-status",
      label: "Left Status Ribbon",
      role: "session-status",
      colorRole: "green-status",
      groupId: "hero-wall",
      priority: 20,
      position: [-5.45, 3.0, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 3.6,
        height: 0.75,
      },
    },
    {
      id: "hero-right-status",
      label: "Right Participants Ribbon",
      role: "participants",
      colorRole: "green-status",
      groupId: "hero-wall",
      priority: 30,
      position: [5.45, 3.0, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 3.6,
        height: 0.75,
      },
    },
    {
      id: "hero-timer-ribbon",
      label: "Upper Timer Ribbon",
      role: "timer-ribbon",
      colorRole: "cyan-data",
      groupId: "hero-wall",
      priority: 40,
      position: [0, 4.20, -8.8],
      rotation: [0, 0, 0],
      size: {
        width: 8.2,
        height: 0.65,
      },
    },
    {
      id: "hero-range-scoreboard",
      label: "Range Scoreboard Monitor",
      role: "range-scoreboard",
      colorRole: "amber-alert",
      groupId: "hero-wall",
      priority: 50,
      position: [-8.00, 1.8, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 3.15,
        height: 1.05,
      },
    },
    {
      id: "hero-music-status",
      label: "Music Status Monitor",
      role: "music-status",
      colorRole: "cyan-data",
      groupId: "hero-wall",
      priority: 60,
      position: [8.0, 1.8, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 3.15,
        height: 1.05,
      },
    },
    {
      id: "hero-system-status",
      label: "System Status Monitor",
      role: "system-status",
      colorRole: "green-status",
      groupId: "hero-wall",
      priority: 70,
      position: [-4.85, 1.2, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 1.65,
        height: 0.72,
      },
    },
    {
      id: "hero-data-panel-left",
      label: "Left Data Panel",
      role: "data-panel",
      colorRole: "cyan-data",
      groupId: "hero-wall",
      priority: 80,
      position: [-6.65, 3.95, -8.8],
      rotation: [0, 0, 0],
      size: {
        width: 1.45,
        height: 0.48,
      },
    },
    {
      id: "hero-data-panel-right",
      label: "Right Data Panel",
      role: "data-panel",
      colorRole: "cyan-data",
      groupId: "hero-wall",
      priority: 90,
      position: [6.65, 3.95, -8.8],
      rotation: [0, 0, 0],
      size: {
        width: 1.45,
        height: 0.48,
      },
    },
    {
      id: "hero-data-panel-lower",
      label: "Lower Data Panel",
      role: "data-panel",
      colorRole: "green-status",
      groupId: "hero-wall",
      priority: 100,
      position: [4.85, 1.1, -8.82],
      rotation: [0, 0, 0],
      size: {
        width: 1.65,
        height: 0.72,
      },
    },
  ],
  jukebox: {
    id: "control-room-jukebox",
    label: "Control Room Jukebox",
    position: [-9.15, 0, 1.15],
    rotation: [0, Math.PI / 2, 0],
    cabinetSize: {
      width: 1.45,
      height: 2.25,
      depth: 0.62,
    },
    screenSurfaces: [
      {
        id: "jukebox-now-playing",
        label: "Now Playing",
        role: "now-playing",
        colorRole: "blue-main",
        localPosition: [0, 1.58, 0.34],
        localRotation: [0, 0, 0],
        size: {
          width: 1.02,
          height: 0.46,
        },
      },
      {
        id: "jukebox-playlist",
        label: "Playlist",
        role: "playlist",
        colorRole: "green-status",
        localPosition: [-0.46, 1.08, 0.35],
        localRotation: [0, 0, 0],
        size: {
          width: 0.38,
          height: 0.58,
        },
      },
      {
        id: "jukebox-status-source",
        label: "Source Status",
        role: "status-source",
        colorRole: "cyan-data",
        localPosition: [0.46, 1.08, 0.35],
        localRotation: [0, 0, 0],
        size: {
          width: 0.38,
          height: 0.58,
        },
      },
      {
        id: "jukebox-controls-help",
        label: "Controls Help",
        role: "controls-help",
        colorRole: "magenta-accent",
        localPosition: [0, 2.02, 0.36],
        localRotation: [0, 0, 0],
        size: {
          width: 1.08,
          height: 0.18,
        },
      },
    ],
    speakerZones: [
      {
        id: "jukebox-left-speaker",
        label: "Left Speaker",
        localPosition: [-0.48, 0.37, 0.35],
        localRotation: [0, 0, 0],
        size: {
          width: 0.28,
          height: 0.44,
        },
      },
      {
        id: "jukebox-right-speaker",
        label: "Right Speaker",
        localPosition: [0.48, 0.37, 0.35],
        localRotation: [0, 0, 0],
        size: {
          width: 0.28,
          height: 0.44,
        },
      },
      {
        id: "jukebox-lower-bass",
        label: "Lower Bass Grille",
        localPosition: [0, 0.18, 0.36],
        localRotation: [0, 0, 0],
        size: {
          width: 0.58,
          height: 0.22,
        },
      },
    ],
    controlZones: [
      {
        id: "jukebox-toggle-playback",
        label: "Play / Pause",
        role: "toggle-playback",
        localPosition: [-0.36, 0.82, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.24,
          height: 0.22,
        },
        phaseStatus: "action-backed",
      },
      {
        id: "jukebox-shuffle",
        label: "Shuffle",
        role: "shuffle",
        localPosition: [-0.12, 0.82, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.24,
          height: 0.22,
        },
        phaseStatus: "action-backed",
      },
      {
        id: "jukebox-retry",
        label: "Retry",
        role: "retry",
        localPosition: [0.12, 0.82, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.24,
          height: 0.22,
        },
        phaseStatus: "action-backed",
      },
      {
        id: "jukebox-next",
        label: "Next",
        role: "next",
        localPosition: [0.36, 0.82, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.24,
          height: 0.22,
        },
        phaseStatus: "planned",
      },
      {
        id: "jukebox-playlist-change",
        label: "Playlist Change",
        role: "playlist-change",
        localPosition: [-0.32, 0.52, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.24,
          height: 0.14,
        },
        phaseStatus: "planned",
      },
      {
        id: "jukebox-page-up",
        label: "Page Up",
        role: "page-up",
        localPosition: [0, 0.52, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.2,
          height: 0.14,
        },
        phaseStatus: "planned",
      },
      {
        id: "jukebox-page-down",
        label: "Page Down",
        role: "page-down",
        localPosition: [0.32, 0.52, 0.38],
        localRotation: [0, 0, 0],
        size: {
          width: 0.24,
          height: 0.14,
        },
        phaseStatus: "planned",
      },
    ],
  },
} satisfies LevelConfig;
